export const GET_ALL_ROOMS = "GET_ALL_ROOMS";
export const GET_ROOMS_SUCCESS = "GET_ROOMS_SUCCESS";
export const GET_ROOMS_FAILURE = "GET_ROOMS_FAILURE";
export const FILTER_ROOMS_BY_PRICE = "FILTER_ROOMS_BY_PRICE";
export const GET_ROOM_BY_ID = "GET_ROOM_BY_ID";